### ISSUE TITLE
Ocultar contraseña

### ISSUE THREAD

**Issue by vgomezd3** [dapanas/stats001#17]
Por favor ocultar la contraseña con \* cuando se realiza la configuración de la base de datos
de los servidores.

Gracias!

**Comment by chesstrian** [comment]
Adicionalmente agregar checkbox que permita ver la contraseña.

**Comment by chesstrian** [comment]
chesstrian/stats001@b0162667eb81341066bcf88de4c64005d4387082 resolves this issue.
